[crosstool]
  [crosstool.version]
    major = "1.2"
    minor = "release"

  [crosstool.toolchain]
    arm-linux-gnueabi =  {arch = "arm", target = "arm-linux-gnueabi"}
    arm-linux-gnueabihf =  {arch = "arm", target = "arm-linux-gnueabihf"}
    aarch64-linux-gnueabi = {arch = "arm", target = "aarch64-linux-gnueabi"}
    aarch64-linux-gnueabihf = {arch = "arm", target = "aarch64-linux-gnueabihf"}

[package]
  [package.version]
  gcc = "12.2.0"
  binutils = "2.40"
  glibc = "2.37"
  linux = "6.1.27"
  gmp = "6.2.1"
  mpc = "1.3.1"
  mpfr = "4.2.0"
  isl = "0.26"

  [package.address]
    prime = {gnu = "https://mirrors.tuna.tsinghua.edu.cn", linux="https://mirrors.tuna.tsinghua.edu.cn", isl="https://libisl.sourceforge.io"}
    proxy = {gnu = "https://ftp.gnu.org/", linux="https://mirrors.edge.kernel.org/pub/linux", isl="https://libisl.sourceforge.io"}